PersoTrainer/PersoTrainer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Trainer.views import *
from django.contrib.auth import views
from django.views.generic import RedirectView
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login, name = 'login'),
    url(r'^home/$', home),
    url(r'^register/$', register),
    url(r'^register/success/$', register_success),
    url(r'^accounts/login/$', views.login, name = 'login'),
    url(r'^logout/$', logout_page),
    url(r'', include('Trainer.urls', namespace= 'Trainer')),      
]

PersoTrainer/Trainer/urls.py
from django.conf.urls import url
from . import views_act, views_myAct, views, views_chat

urlpatterns = [

    url(r'^activities/$', views_act.activities, name = 'activities'),
    url(r'^activities/detail/(?P<activity_pk>\d+)/$', views_act.activity_detail, name='activity_detail'),
    url(r'^add_act$', views_act.add_act, name = 'add_act'),

    url(r'^MyActivities/$', views_myAct.MyActivities, name = 'MyActivities'),

    url(r'^chatRoom/$', views_chat.index, name='index'),
    # url(r'^(?P<chat_room_id>\d+)/$', views_chat.chat_room, name='chat_room'),


    url(r'^post/$', views_chat.Post, name='post'),
    url(r'^chat_room/$', views_chat.chat_room, name='chat_room'),

]

PersoTrainer/Trainer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return "User: " + self.user

class Activities (models.Model):
    name = models.CharField(max_length=200, blank=False, unique=True)
    detail = models.TextField(max_length = 1000, blank = False)
    point = models.IntegerField(default=0, blank= False)
    InProgress = models.BooleanField(default=False)

    def __str__(self):
        return 'Activity {} do {} and gain {}{}'.format(self.name, self.detail, self.point, self.InProgress)

class MyActivities (models.Model):
    add_date = models.DateTimeField(blank=False)
    user = models.ForeignKey('auth.User', blank=False)
    activities = models.ForeignKey(Activities)

    def __str__(self):
        return 'User {} with detail {} at {}'.format(self.user, self.activities, self.add_date)


class ChatRoom(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    message = models.CharField(max_length=200)

    def __unicode__(self):
        return self.message

PersoTrainer/Trainer/forms.py
import re
from .models import Activities
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _



# class activitiesForm(forms.ModelForm):
#     class Meta:
#         model = Activities
#         fields = ('name', 'point', 'detail')



class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

PersoTrainer/Trainer/views.py
from django.shortcuts import render

# Create your views here.
from Trainer.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from PersoTrainer import settings



@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request)

    return render(request,
    'registration/register.html', {'form': form})

@csrf_protect
def register_success(request):
    return render_to_response(
    'registration/success.html',{},
    RequestContext(request))

@csrf_protect
def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

@csrf_protect
@login_required
def home(request):
     return render_to_response(
    'home.html',
    { 'user': request.user }
    )

PersoTrainer/Trainer/templates/MyActivities/MyActivities.html
{% extends "base.html" %}
{% block content %}


{% block head %}{{user.username}}'s Activities{% endblock %}

{% for activity in Myact %}

<div id="activity_{{ activity.pk }}">
  <P><a>{{ activity.name }}: {{ activity.detail }} and Point {{ activity.point }}</a></P>



</div>

{% empty %}
  <P>No activities found</p>
{% endfor %}
{% endblock%}

PersoTrainer/templates/Activities/activities.html
<!-- activities.html -->
{% extends "base.html" %}
{% block content %}


{% block head %}Activities{% endblock %}

{% for activity in activities %}

<div id="activity_{{ activity.pk }}">
  <P><a href="{% url 'Trainer:activity_detail' activity_pk=activity.pk %}">{{ activity.name }}</a></p>

  <form method="POST" action = "url 'add_act' %">{% csrf_token %}
    <input type="hidden" name="pk" value="{{activity.pk}}">
    <button type="submit">Add activity</button>
  </form>

</div>

{% empty %}
  <P>No activities found</p>
{% endfor %}
{% endblock%}

PersoTrainer/templates/Activities/activity_detail.html
<!-- detail of an activity -->

{% extends 'base.html' %}

{% block content %}

<h2 id='activity_detail_title'>Activity Detail</h2>

<p id="activity_name"> Name: {{ activity.name }}</p>
<P><span id="activity_detail"> Detail: {{ activity.detail }}</span></p>
<p><span id="activity_point"> Point: {{ activity.point }}</span></p>

{% endblock %}

PersoTrainer/templates/MyActivities/MyActivities.html
{% extends "base.html" %}
{% block content %}


{% block head %}{{user.username}}'s Activities{% endblock %}

{% for activity in Myact %}

<div id="activity_{{ activity.pk }}">
  <P><a>{{ activity.name }}: {{ activity.detail }} and Point {{ activity.point }}</a></P>



</div>

{% empty %}
  <P>No activities found</p>
{% endfor %}
{% endblock%}

PersoTrainer/templates/base.html
<!-- base.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href=" {% static 'css/base.css'%}">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/home.css'%}">
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <h1>{% block head %}{% endblock %}</h1>
            {% block content %}{% endblock %}
        </div>

        {% block nav %}
        <ul id="nav">
            <li>{% block nav-home %}<a class="active" href="#home">Home</a>{% endblock %}</li>
            <li>{% block nav-activities %}<a href="{% url 'Trainer:activities' %}">Activities</a>{% endblock %}</li>
            <li>{% block nav-MyActivities %}<a href="{% url 'Trainer:MyActivities' %}">My Activities </a>{% endblock %}</li>
            <li>{% block nav-chatRoom %}<a href="{% url 'Trainer:index' %}">Chat Room </a>{% endblock %}</li>

            {% if user.is_authenticated %}
            <li style="float:right"><a onclick="window.location.href='/logout/'">Logout</a></li>
            {% else %}

            {% endif %}

          </ul>
          {% endblock %}
    </div>
</body>
</html>

PersoTrainer/templates/chat/chat_room.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
{% for obj in chat %}
    {% if obj.user == request.user %}
        <li class="text-right list-group-item">{{ obj.message }}</li>
    {% else %}
        <li class="text-left list-group-item">{{ obj.message }}</li>
    {% endif %}
{% empty %}
    <li class="text-right list-group-item">No messages yet!</li>
{% endfor %}
{% endblock%}

PersoTrainer/templates/chat/index.html
{% extends "base.html" %}

{% block content %}

{% load staticfiles %}

<html>

<head>
    <title>Chat Panel</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'chat.css' %}">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>

<body>
    <div id="chat-body" class="panel panel-default">
        <div class="panel-heading">Chat Box</div>
        <div id="msg-list-div" class="panel-body">
            <ul id="msg-list" class="list-group">
                {% for obj in chat %}
                    {% if obj.user == request.user %}
                        <li class="text-right list-group-item">{{ obj.message }}</li>
                    {% else %}
                        <li class="text-left list-group-item">{{ obj.message }}</li>
                    {% endif %}
                {% empty %}
                    <li class="text-right list-group-item">No messages yet!</li>
                {% endfor %}
                <script>
                    var chatlist = document.getElementById('msg-list-div');
                    chatlist.scrollTop = chatlist.scrollHeight;
                </script>
            </ul>
        </div>
    </div>

    <form id="chat-form" method="post" action="/post/">{% csrf_token %}
        <div id="chat-bottom" class="input-group">
            <input type="text" id="chat-msg" name="chat-msg" class="form-control"/>
            <span class="input-group-btn">
                <input class="btn btn-default" id="send" type="submit" value="Send"/>
            </span>
        </div>
    </form>
</body>

<script src="{% static 'chat.js' %}"></script>
</html>
{% endblock%}

PersoTrainer/templates/home.html
<!-- home.html -->

{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Welcome PersTrainer {% endblock %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css '%}">
{% endblock %}
{% block content %}
    <h1> Welcome {{ user.username }} !!! </h1>

{% endblock %}